### PR TITLE
protoplugfiles: add karplus generator and includes/vic

### PR DESCRIPTION
**Pull request by sonoro1234**
Congratulations for protoplug, is very stable and is Lua.
This pull request has a karplus string generator plus some needed includes.

### CODE REVIEW

**Comment by pac-dev** [comment]
Outstanding! And your delay line is the best. 

This PR also raises the interesting question of code redundancy in /inlude/<user> folders. I'm just being a maniac here but maybe it would be better for you to just modify my cookbook_filters.lua instead of adding another? (and possibly add your credit to it, heck there are already 3 authors). Especially considering that the phaseDelay function you added is super useful, so it's a strict improvement over the previous version. Of course a seperate file would have been necessary if you had made breaking changes, but this is not the case here.

**Comment by SpotlightKid** [comment]
I had the same thoughts about code re-use. Maybe split this into two PRs? One for include files consolidation (i.e. merging the cookbook filters implementations) and one for the actual karplus example?

I also think that include sub-directories should have names based on category or application not the developer.

**Comment by pac-dev** [comment]
I agree that having username subfolders in include/ is a bit weird. I guess when I get some time I will just merge this PR and then restructure the include folder (keeping `core`, `protojuce`; and replacing the username folders with `dsp` and `gui-extras`?). Actually it's quite simple and there's no file to merge (the modified cookbook filters is just better).

**Comment by sonoro1234** [comment]
Fell free to rework as you need.

**Comment by sonoro1234** [comment]
delay line was 1 sample longer than needed

**Pull request merged**
